{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "9f8e26db-f0b8-4cfe-b715-101822d8b8d1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1, Loss: 39.0878, Val Loss: 17.7024\n",
      "✅ Model saved!\n",
      "Epoch 2, Loss: 23.0281, Val Loss: 15.3196\n",
      "✅ Model saved!\n",
      "Epoch 3, Loss: 19.9300, Val Loss: 10.9493\n",
      "✅ Model saved!\n",
      "Epoch 4, Loss: 21.1389, Val Loss: 12.8873\n",
      "Epoch 5, Loss: 14.7481, Val Loss: 9.6938\n",
      "✅ Model saved!\n",
      "Epoch 6, Loss: 13.5513, Val Loss: 9.3740\n",
      "✅ Model saved!\n",
      "Epoch 7, Loss: 8.0249, Val Loss: 11.9533\n",
      "Epoch 8, Loss: 10.9404, Val Loss: 17.0274\n",
      "Epoch 9, Loss: 8.8575, Val Loss: 7.7481\n",
      "✅ Model saved!\n",
      "Epoch 10, Loss: 4.7910, Val Loss: 7.7974\n",
      "Epoch 11, Loss: 6.1452, Val Loss: 9.9911\n",
      "Epoch 12, Loss: 8.4526, Val Loss: 11.3663\n",
      "Epoch 13, Loss: 9.9895, Val Loss: 12.1899\n",
      "Epoch 14, Loss: 10.1012, Val Loss: 11.5166\n",
      "Epoch 15, Loss: 9.4074, Val Loss: 19.3458\n"
     ]
    }
   ],
   "source": [
    "# train_model.py\n",
    "\n",
    "import os\n",
    "import torch\n",
    "import torchvision.transforms as transforms\n",
    "from torchvision.datasets import ImageFolder\n",
    "from torch.utils.data import DataLoader, random_split\n",
    "import torch.nn as nn\n",
    "import torch.optim as optim\n",
    "from torchvision import models\n",
    "\n",
    "# Config\n",
    "data_dir = 'data/train'\n",
    "num_epochs = 15\n",
    "batch_size = 16\n",
    "learning_rate = 0.001\n",
    "model_path = 'models/best_model.pth'\n",
    "\n",
    "# Transforms\n",
    "transform = transforms.Compose([\n",
    "    transforms.Resize((224, 224)),\n",
    "    transforms.ToTensor(),\n",
    "])\n",
    "\n",
    "# Dataset and Dataloader\n",
    "dataset = ImageFolder(root=data_dir, transform=transform)\n",
    "class_names = dataset.classes\n",
    "num_classes = len(class_names)\n",
    "\n",
    "train_size = int(0.8 * len(dataset))\n",
    "val_size = len(dataset) - train_size\n",
    "train_ds, val_ds = random_split(dataset, [train_size, val_size])\n",
    "train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True)\n",
    "val_loader = DataLoader(val_ds, batch_size=batch_size)\n",
    "\n",
    "# Model\n",
    "model = models.resnet18(weights='IMAGENET1K_V1')\n",
    "model.fc = nn.Linear(model.fc.in_features, num_classes)\n",
    "\n",
    "device = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
    "model = model.to(device)\n",
    "\n",
    "# Loss and optimizer\n",
    "criterion = nn.CrossEntropyLoss()\n",
    "optimizer = optim.Adam(model.parameters(), lr=learning_rate)\n",
    "\n",
    "best_val_loss = float('inf')\n",
    "for epoch in range(num_epochs):\n",
    "    model.train()\n",
    "    running_loss = 0\n",
    "    for imgs, labels in train_loader:\n",
    "        imgs, labels = imgs.to(device), labels.to(device)\n",
    "        optimizer.zero_grad()\n",
    "        outputs = model(imgs)\n",
    "        loss = criterion(outputs, labels)\n",
    "        loss.backward()\n",
    "        optimizer.step()\n",
    "        running_loss += loss.item()\n",
    "\n",
    "    val_loss = 0\n",
    "    model.eval()\n",
    "    with torch.no_grad():\n",
    "        for imgs, labels in val_loader:\n",
    "            imgs, labels = imgs.to(device), labels.to(device)\n",
    "            outputs = model(imgs)\n",
    "            val_loss += criterion(outputs, labels).item()\n",
    "\n",
    "    print(f\"Epoch {epoch+1}, Loss: {running_loss:.4f}, Val Loss: {val_loss:.4f}\")\n",
    "\n",
    "    if val_loss < best_val_loss:\n",
    "        best_val_loss = val_loss\n",
    "        torch.save(model.state_dict(), model_path)\n",
    "        print(\"✅ Model saved!\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f16b0f22-26d3-48b0-92ae-4d2e02a83d02",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
