"""
PDF Exporter - Export classification results to PDF format
"""

import os
from datetime import datetime
from typing import Dict, List, Any, Optional
from PIL import Image, ImageDraw, ImageFont
import io


class PDFExporter:
    """Handles PDF export operations"""
    
    def __init__(self):
        self.export_dir = "exports"
        os.makedirs(self.export_dir, exist_ok=True)
        
        # Try to import reportlab for PDF generation
        try:
            from reportlab.lib.pagesizes import letter, A4
            from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image as RLImage, Table, TableStyle
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib.units import inch
            from reportlab.lib import colors
            from reportlab.lib.enums import TA_CENTER, TA_LEFT
            
            self.reportlab_available = True
            self.letter = letter
            self.A4 = A4
            self.SimpleDocTemplate = SimpleDocTemplate
            self.Paragraph = Paragraph
            self.Spacer = Spacer
            self.RLImage = RLImage
            self.Table = Table
            self.TableStyle = TableStyle
            self.getSampleStyleSheet = getSampleStyleSheet
            self.ParagraphStyle = ParagraphStyle
            self.inch = inch
            self.colors = colors
            self.TA_CENTER = TA_CENTER
            self.TA_LEFT = TA_LEFT
            
        except ImportError:
            self.reportlab_available = False
    
    def export_single(self, result_data: Dict[str, Any], filename: str) -> str:
        """
        Export a single classification result to PDF
        
        Args:
            result_data: Dictionary containing classification result
            filename: Filename without extension
            
        Returns:
            Path to exported PDF file
        """
        if not self.reportlab_available:
            return self._fallback_export_single(result_data, filename)
        
        filepath = os.path.join(self.export_dir, f"{filename}.pdf")
        
        # Create PDF document
        doc = SimpleDocTemplate(filepath, pagesize=self.A4)
        styles = getSampleStyleSheet()
        story = []
        
        # Title
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            spaceAfter=30,
            alignment=self.TA_CENTER,
            textColor=self.colors.darkblue
        )
        story.append(Paragraph("FlavorSnap Classification Report", title_style))
        story.append(Spacer(1, 20))
        
        # Classification result
        result_style = ParagraphStyle(
            'ResultStyle',
            parent=styles['Normal'],
            fontSize=14,
            spaceAfter=12,
            alignment=self.TA_LEFT
        )
        
        story.append(Paragraph(f"<b>Predicted Class:</b> {result_data.get('predicted_class', 'N/A')}", result_style))
        story.append(Paragraph(f"<b>Confidence:</b> {result_data.get('confidence', 0):.2%}", result_style))
        story.append(Paragraph(f"<b>Timestamp:</b> {result_data.get('timestamp', 'N/A')}", result_style))
        story.append(Spacer(1, 20))
        
        # Add image if present
        if result_data.get('image_data'):
            try:
                # Convert PIL Image to reportlab compatible format
                img_buffer = io.BytesIO()
                result_data['image_data'].save(img_buffer, format='PNG')
                img_buffer.seek(0)
                
                # Add image to PDF (scaled appropriately)
                rl_image = self.RLImage(img_buffer, width=4*self.inch, height=4*self.inch)
                story.append(rl_image)
                story.append(Spacer(1, 20))
            except Exception as e:
                story.append(Paragraph(f"<i>Image could not be included: {str(e)}</i>", result_style))
        
        # Footer
        footer_style = ParagraphStyle(
            'FooterStyle',
            parent=styles['Normal'],
            fontSize=10,
            alignment=self.TA_CENTER,
            textColor=self.colors.grey
        )
        story.append(Spacer(1, 30))
        story.append(Paragraph(f"Generated by FlavorSnap on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", footer_style))
        
        # Build PDF
        doc.build(story)
        
        return filepath
    
    def export_batch(self, results: List[Dict[str, Any]], filename: str) -> str:
        """
        Export multiple classification results to PDF
        
        Args:
            results: List of classification result dictionaries
            filename: Filename without extension
            
        Returns:
            Path to exported PDF file
        """
        if not self.reportlab_available:
            return self._fallback_export_batch(results, filename)
        
        filepath = os.path.join(self.export_dir, f"{filename}.pdf")
        
        # Create PDF document
        doc = SimpleDocTemplate(filepath, pagesize=self.A4)
        styles = getSampleStyleSheet()
        story = []
        
        # Title
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            spaceAfter=30,
            alignment=self.TA_CENTER,
            textColor=self.colors.darkblue
        )
        story.append(Paragraph("FlavorSnap Batch Classification Report", title_style))
        story.append(Spacer(1, 20))
        
        # Summary
        summary_style = ParagraphStyle(
            'SummaryStyle',
            parent=styles['Normal'],
            fontSize=12,
            spaceAfter=12
        )
        
        classes = [r.get('predicted_class', '') for r in results]
        class_counts = {}
        for cls in classes:
            class_counts[cls] = class_counts.get(cls, 0) + 1
        
        story.append(Paragraph(f"<b>Total Classifications:</b> {len(results)}", summary_style))
        story.append(Paragraph(f"<b>Unique Classes:</b> {len(class_counts)}", summary_style))
        story.append(Paragraph(f"<b>Average Confidence:</b> {sum(r.get('confidence', 0) for r in results) / len(results):.2%}", summary_style))
        story.append(Spacer(1, 20))
        
        # Results table
        table_data = [['#', 'Class', 'Confidence', 'Timestamp']]
        for i, result in enumerate(results[:50]):  # Limit to first 50 for readability
            table_data.append([
                str(i + 1),
                result.get('predicted_class', 'N/A'),
                f"{result.get('confidence', 0):.2%}",
                result.get('timestamp', 'N/A')[:19] if result.get('timestamp') else 'N/A'
            ])
        
        table = self.Table(table_data)
        table.setStyle(self.TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), self.colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), self.colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), self.colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, self.colors.black)
        ]))
        
        story.append(table)
        
        if len(results) > 50:
            story.append(Spacer(1, 12))
            story.append(Paragraph(f"<i>Note: Showing first 50 of {len(results)} results</i>", summary_style))
        
        # Footer
        footer_style = ParagraphStyle(
            'FooterStyle',
            parent=styles['Normal'],
            fontSize=10,
            alignment=self.TA_CENTER,
            textColor=self.colors.grey
        )
        story.append(Spacer(1, 30))
        story.append(Paragraph(f"Generated by FlavorSnap on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", footer_style))
        
        # Build PDF
        doc.build(story)
        
        return filepath
    
    def _fallback_export_single(self, result_data: Dict[str, Any], filename: str) -> str:
        """
        Fallback method when reportlab is not available - creates an image instead
        """
        filepath = os.path.join(self.export_dir, f"{filename}_report.png")
        
        # Create a simple image report
        width, height = 800, 1000
        img = Image.new('RGB', (width, height), 'white')
        draw = ImageDraw.Draw(img)
        
        try:
            title_font = ImageFont.truetype("arial.ttf", 32)
            text_font = ImageFont.truetype("arial.ttf", 18)
        except:
            title_font = ImageFont.load_default()
            text_font = ImageFont.load_default()
        
        # Title
        draw.text((50, 50), "FlavorSnap Classification Report", fill='black', font=title_font)
        
        # Content
        y_position = 150
        line_height = 40
        
        draw.text((50, y_position), f"Predicted Class: {result_data.get('predicted_class', 'N/A')}", fill='black', font=text_font)
        y_position += line_height
        
        draw.text((50, y_position), f"Confidence: {result_data.get('confidence', 0):.2%}", fill='black', font=text_font)
        y_position += line_height
        
        draw.text((50, y_position), f"Timestamp: {result_data.get('timestamp', 'N/A')}", fill='black', font=text_font)
        y_position += line_height * 2
        
        # Add image if present
        if result_data.get('image_data'):
            try:
                # Resize and place the classified image
                classified_img = result_data['image_data'].copy()
                classified_img.thumbnail((600, 400))
                img.paste(classified_img, (100, y_position))
                y_position += 450
            except:
                pass
        
        # Footer
        draw.text((50, height - 100), f"Generated by FlavorSnap on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", fill='gray', font=text_font)
        
        img.save(filepath, "PNG")
        
        return filepath
    
    def _fallback_export_batch(self, results: List[Dict[str, Any]], filename: str) -> str:
        """
        Fallback method when reportlab is not available - creates an image instead
        """
        filepath = os.path.join(self.export_dir, f"{filename}_report.png")
        
        # Create a simple image report
        width, height = 1200, 1600
        img = Image.new('RGB', (width, height), 'white')
        draw = ImageDraw.Draw(img)
        
        try:
            title_font = ImageFont.truetype("arial.ttf", 28)
            text_font = ImageFont.truetype("arial.ttf", 16)
        except:
            title_font = ImageFont.load_default()
            text_font = ImageFont.load_default()
        
        # Title
        draw.text((50, 50), "FlavorSnap Batch Classification Report", fill='black', font=title_font)
        
        # Summary
        y_position = 120
        line_height = 35
        
        classes = [r.get('predicted_class', '') for r in results]
        class_counts = {}
        for cls in classes:
            class_counts[cls] = class_counts.get(cls, 0) + 1
        
        draw.text((50, y_position), f"Total Classifications: {len(results)}", fill='black', font=text_font)
        y_position += line_height
        
        draw.text((50, y_position), f"Unique Classes: {len(class_counts)}", fill='black', font=text_font)
        y_position += line_height
        
        draw.text((50, y_position), f"Average Confidence: {sum(r.get('confidence', 0) for r in results) / len(results):.2%}", fill='black', font=text_font)
        y_position += line_height * 2
        
        # Results table (simplified)
        draw.text((50, y_position), "Classification Results:", fill='black', font=title_font)
        y_position += line_height * 1.5
        
        # Table header
        draw.text((50, y_position), "#", fill='black', font=text_font)
        draw.text((150, y_position), "Class", fill='black', font=text_font)
        draw.text((400, y_position), "Confidence", fill='black', font=text_font)
        draw.text((600, y_position), "Timestamp", fill='black', font=text_font)
        y_position += line_height
        
        # Table rows (limited)
        for i, result in enumerate(results[:30]):  # Limit to first 30
            draw.text((50, y_position), str(i + 1), fill='black', font=text_font)
            draw.text((150, y_position), result.get('predicted_class', 'N/A')[:20], fill='black', font=text_font)
            draw.text((400, y_position), f"{result.get('confidence', 0):.2%}", fill='black', font=text_font)
            draw.text((600, y_position), result.get('timestamp', 'N/A')[:19], fill='black', font=text_font)
            y_position += line_height
        
        if len(results) > 30:
            draw.text((50, y_position), f"... and {len(results) - 30} more results", fill='gray', font=text_font)
        
        # Footer
        draw.text((50, height - 100), f"Generated by FlavorSnap on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", fill='gray', font=text_font)
        
        img.save(filepath, "PNG")
        
        return filepath
