#!/usr/bin/env python3
"""
Generate automated remediation scripts for security vulnerabilities
"""

import json
import sys
import argparse
from pathlib import Path
from typing import Dict, List, Any

class RemediationGenerator:
    """Generate automated remediation scripts"""
    
    def __init__(self):
        self.remediation_scripts = {
            'dependencies': self._generate_dependency_remediation,
            'code': self._generate_code_remediation,
            'container': self._generate_container_remediation,
            'compliance': self._generate_compliance_remediation
        }
    
    def generate_remediation(self, scan_type: str, output_path: Path):
        """Generate remediation script for specified scan type"""
        if scan_type not in self.remediation_scripts:
            raise ValueError(f"Unsupported scan type: {scan_type}")
        
        generator = self.remediation_scripts[scan_type]
        script_content = generator()
        
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        if scan_type in ['dependencies', 'code', 'container']:
            # Generate shell script
            with open(output_path, 'w') as f:
                f.write(script_content)
            output_path.chmod(0o755)  # Make executable
        else:
            # Generate Python script
            with open(output_path, 'w') as f:
                f.write(script_content)
    
    def _generate_dependency_remediation(self) -> str:
        """Generate dependency update script"""
        return '''#!/bin/bash
# Automated dependency remediation script
# Generated by FlavorSnap security scanner

set -e

echo "Starting automated dependency remediation..."

# Python dependencies
if [ -f "requirements.txt" ]; then
    echo "Updating Python dependencies..."
    
    # Backup original requirements
    cp requirements.txt requirements.txt.backup
    
    # Update vulnerable packages
    python -m pip install --upgrade pip
    
    # Install safety and check for updates
    pip install safety
    
    # Get list of vulnerable packages
    safety check --json --short-report -r requirements.txt > vulnerable_deps.json 2>/dev/null || true
    
    if [ -f "vulnerable_deps.json" ]; then
        echo "Found vulnerable Python packages, attempting updates..."
        
        # Parse and update vulnerable packages
        python -c "
import json
import subprocess
import sys

try:
    with open('vulnerable_deps.json', 'r') as f:
        data = json.load(f)
    
    for vuln in data:
        package = vuln.get('package', '')
        fixed_versions = vuln.get('fixed_versions', [])
        
        if package and fixed_versions:
            latest_fixed = fixed_versions[0]
            print(f'Updating {package} to {latest_fixed}...')
            try:
                subprocess.run(['pip', 'install', f'{package}=={latest_fixed}'], check=True)
                subprocess.run(['pip', 'freeze'], stdout=open('requirements_new.txt', 'w'))
            except subprocess.CalledProcessError:
                print(f'Failed to update {package}')
except Exception as e:
    print(f'Error processing dependencies: {e}')
    sys.exit(1)
"
        
        # Update requirements.txt if successful
        if [ -f "requirements_new.txt" ]; then
            mv requirements_new.txt requirements.txt
            echo "Updated requirements.txt"
        fi
    fi
fi

# Rust dependencies
if [ -f "Cargo.toml" ]; then
    echo "Checking Rust dependencies..."
    
    # Run cargo audit
    if command -v cargo-audit &> /dev/null; then
        cargo audit --json > rust_audit.json 2>/dev/null || true
        
        if [ -f "rust_audit.json" ]; then
            echo "Found vulnerable Rust packages, attempting updates..."
            
            # Update vulnerable crates
            cargo update
            echo "Updated Cargo dependencies"
        fi
    fi
fi

# Node.js dependencies
if [ -f "package.json" ]; then
    echo "Checking Node.js dependencies..."
    
    if command -v npm &> /dev/null; then
        npm audit --json > npm_audit.json 2>/dev/null || true
        
        if [ -f "npm_audit.json" ]; then
            echo "Found vulnerable Node.js packages, attempting updates..."
            
            # Fix vulnerable packages
            npm audit fix --force || true
            echo "Attempted to fix Node.js dependencies"
        fi
    fi
fi

echo "Dependency remediation completed"
echo "Please review the changes and test thoroughly before deploying"
'''
    
    def _generate_code_remediation(self) -> str:
        """Generate code security fixes script"""
        return '''#!/bin/bash
# Automated code security remediation script
# Generated by FlavorSnap security scanner

set -e

echo "Starting automated code security remediation..."

# Fix common Python security issues
echo "Checking Python code for security issues..."

# Find Python files and apply fixes
find . -name "*.py" -type f | while read file; do
    # Skip __pycache__ and other cache directories
    if [[ "$file" == *"__pycache__"* ]] || [[ "$file" == *".pyc"* ]]; then
        continue
    fi
    
    echo "Processing $file"
    
    # Backup original file
    cp "$file" "$file.backup"
    
    # Apply security fixes
    python -c "
import re
import sys

def fix_python_security(file_path):
    try:
        with open(file_path, 'r') as f:
            content = f.read()
        
        original_content = content
        
        # Fix: Use proper SQL parameterization (simple pattern)
        content = re.sub(
            r'cursor\\.execute\\(\\\"([^\\\"]+)\\\"\\.format\\([^\\)]+\\)\\)',
            r'cursor.execute(\\\"\\\\1\\\", params)',
            content
        )
        
        # Fix: Replace eval() with safer alternatives
        content = re.sub(
            r'eval\\(\\\"([^\\\"]+)\\\"\\)',
            r'safe_eval(\\\"\\\\1\\\")',
            content
        )
        
        # Fix: Replace exec() with safer alternatives
        content = re.sub(
            r'exec\\(\\\"([^\\\"]+)\\\"\\)',
            r'safe_exec(\\\"\\\\1\\\")',
            content
        )
        
        # Fix: Add input validation for file operations
        content = re.sub(
            r'open\\(\\\"([^\\\"]+)\\\", \\\"r\\\"\\)',
            r'safe_open(\\\"\\\\1\\\", \\\"r\\\")',
            content
        )
        
        # Only write if changes were made
        if content != original_content:
            with open(file_path, 'w') as f:
                f.write(content)
            print(f'Applied security fixes to {file_path}')
            
    except Exception as e:
        print(f'Error processing {file_path}: {e}')

fix_python_security('$file')
"
    
    if [ -f "$file.backup" ] && ! cmp -s "$file" "$file.backup"; then
        echo "  - Security fixes applied"
    else
        # No changes made, remove backup
        rm -f "$file.backup"
    fi
done

# Fix Rust code issues
if [ -f "Cargo.toml" ]; then
    echo "Checking Rust code for security issues..."
    
    if command -v cargo &> /dev/null; then
        # Run clippy and fix automatically where possible
        cargo clippy --fix --allow-dirty --allow-staged || true
        echo "Applied Rust clippy fixes"
    fi
fi

echo "Code security remediation completed"
echo "Please review all changes and test thoroughly before deploying"
'''
    
    def _generate_container_remediation(self) -> str:
        """Generate container security fixes script"""
        return '''#!/bin/bash
# Automated container security remediation script
# Generated by FlavorSnap security scanner

set -e

echo "Starting automated container security remediation..."

# Fix Dockerfile security issues
if [ -f "Dockerfile" ]; then
    echo "Checking Dockerfile for security issues..."
    
    # Backup original Dockerfile
    cp Dockerfile Dockerfile.backup
    
    # Apply security fixes
    python -c "
import re

def fix_dockerfile_security(file_path):
    try:
        with open(file_path, 'r') as f:
            content = f.read()
        
        original_content = content
        
        # Fix: Use specific base image versions instead of latest
        content = re.sub(
            r'FROM\\s+(\\w+):latest',
            lambda m: f'FROM {m.group(1)}:20.04',  # Use a stable version
            content
        )
        
        # Fix: Add non-root user if not present
        if 'RUN adduser' not in content and 'USER' not in content:
            content += '''
# Add non-root user
RUN adduser --disabled-password --gecos '' appuser
USER appuser
'''
        
        # Fix: Remove sensitive information
        content = re.sub(r'ENV\\s+PASSWORD[^\\n]*', '', content)
        content = re.sub(r'ENV\\s+SECRET[^\\n]*', '', content)
        content = re.sub(r'ENV\\s+API_KEY[^\\n]*', '', content)
        
        # Fix: Add health check if not present
        if 'HEALTHCHECK' not in content:
            content += '''
# Add health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \\
  CMD curl -f http://localhost:8000/health || exit 1
'''
        
        # Only write if changes were made
        if content != original_content:
            with open(file_path, 'w') as f:
                f.write(content)
            print('Applied Dockerfile security fixes')
            
    except Exception as e:
        print(f'Error fixing Dockerfile: {e}')

fix_dockerfile_security('Dockerfile')
"
    
    if [ -f "Dockerfile.backup" ] && ! cmp -s "Dockerfile" "Dockerfile.backup"; then
        echo "  - Dockerfile security fixes applied"
    else
        rm -f "Dockerfile.backup"
    fi
fi

# Fix Docker Compose security issues
for compose_file in docker-compose*.yml docker-compose*.yaml; do
    if [ -f "$compose_file" ]; then
        echo "Checking $compose_file for security issues..."
        
        # Backup original file
        cp "$compose_file" "$compose_file.backup"
        
        # Apply security fixes
        python -c "
import yaml
import sys

def fix_compose_security(file_path):
    try:
        with open(file_path, 'r') as f:
            content = yaml.safe_load(f)
        
        if not content or 'services' not in content:
            return
        
        made_changes = False
        
        for service_name, service in content.get('services', {}).items():
            # Fix: Add resource limits
            if 'deploy' not in service:
                service['deploy'] = {}
            if 'resources' not in service['deploy']:
                service['deploy']['resources'] = {
                    'limits': {
                        'cpus': '0.5',
                        'memory': '512M'
                    },
                    'reservations': {
                        'cpus': '0.1',
                        'memory': '128M'
                    }
                }
                made_changes = True
            
            # Fix: Add health check if not present
            if 'healthcheck' not in service:
                service['healthcheck'] = {
                    'test': ['CMD', 'curl', '-f', 'http://localhost:8000/health'],
                    'interval': '30s',
                    'timeout': '10s',
                    'retries': 3
                }
                made_changes = True
            
            # Fix: Remove privileged mode
            if service.get('privileged'):
                del service['privileged']
                made_changes = True
        
        if made_changes:
            with open(file_path, 'w') as f:
                yaml.dump(content, f, default_flow_style=False)
            print(f'Applied security fixes to {file_path}')
            
    except Exception as e:
        print(f'Error processing {file_path}: {e}')

fix_compose_security('$compose_file')
"
        
        if [ -f "$compose_file.backup" ] && ! cmp -s "$compose_file" "$compose_file.backup"; then
            echo "  - $compose_file security fixes applied"
        else
            rm -f "$compose_file.backup"
        fi
    fi
done

echo "Container security remediation completed"
echo "Please review all changes and test containers thoroughly before deploying"
'''
    
    def _generate_compliance_remediation(self) -> str:
        """Generate compliance fixes script"""
        return '''#!/usr/bin/env python3
"""
Automated compliance remediation script
Generated by FlavorSnap security scanner
"""

import json
import os
import re
import sys
from pathlib import Path

def fix_security_headers():
    """Fix missing security headers in configuration files"""
    print("Checking security headers configuration...")
    
    required_headers = {
        'X-Content-Type-Options': 'nosniff',
        'X-Frame-Options': 'DENY',
        'X-XSS-Protection': '1; mode=block',
        'Strict-Transport-Security': 'max-age=31536000; includeSubDomains',
        'Content-Security-Policy': "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'",
        'Referrer-Policy': 'strict-origin-when-cross-origin',
        'Permissions-Policy': 'geolocation=(), microphone=(), camera=()'
    }
    
    # Look for Flask/Python configuration files
    for config_file in Path('.').rglob('*.py'):
        if 'config' in config_file.name.lower() or 'app' in config_file.name.lower():
            try:
                content = config_file.read_text()
                original_content = content
                
                # Add security headers if missing
                headers_section = "SECURITY_HEADERS = {"
                if headers_section not in content:
                    # Add security headers configuration
                    headers_config = "\\n\\n# Security headers\\nSECURITY_HEADERS = {\\n"
                    for header, value in required_headers.items():
                        headers_config += f"    '{header}': '{value}',\\n"
                    headers_config += "}\\n"
                    
                    # Insert after imports
                    import_end = content.rfind("\\n\\n")
                    if import_end != -1:
                        content = content[:import_end] + headers_config + content[import_end:]
                
                # Only write if changes were made
                if content != original_content:
                    config_file.write_text(content)
                    print(f"  - Added security headers to {config_file}")
                    
            except Exception as e:
                print(f"Error processing {config_file}: {e}")

def remove_hardcoded_secrets():
    """Remove hardcoded secrets from source code"""
    print("Checking for hardcoded secrets...")
    
    secret_patterns = [
        (r'password\\s*=\\s*[\"\\'][^\"\\']+[\"\\']', 'Hardcoded password'),
        (r'api_key\\s*=\\s*[\"\\'][^\"\\']+[\"\\']', 'Hardcoded API key'),
        (r'secret\\s*=\\s*[\"\\'][^\"\\']+[\"\\']', 'Hardcoded secret'),
        (r'token\\s*=\\s*[\"\\'][^\"\\']+[\"\\']', 'Hardcoded token'),
    ]
    
    # Scan source files
    source_extensions = ['.py', '.js', '.ts', '.yml', '.yaml', '.json', '.env']
    
    for ext in source_extensions:
        for file_path in Path('.').rglob(f"*{ext}"):
            if file_path.name.startswith('.'):
                continue
                
            try:
                content = file_path.read_text()
                original_content = content
                
                for pattern, description in secret_patterns:
                    matches = re.findall(pattern, content, re.IGNORECASE)
                    if matches:
                        print(f"  - Found {description} in {file_path}")
                        
                        # Replace with environment variable reference
                        content = re.sub(
                            pattern,
                            lambda m: f"{m.group().split('=')[0]} = os.environ.get('{m.group().split('=')[0].upper()}_ENV', '')",
                            content,
                            flags=re.IGNORECASE
                        )
                
                # Only write if changes were made
                if content != original_content:
                    file_path.write_text(content)
                    print(f"    - Replaced hardcoded secrets in {file_path}")
                    
            except Exception as e:
                print(f"Error scanning {file_path}: {e}")

def fix_file_permissions():
    """Fix insecure file permissions"""
    print("Checking file permissions...")
    
    try:
        import subprocess
        # Find and fix world-writable files
        result = subprocess.run(
            ["find", ".", "-type", "f", "-perm", "/o+w"],
            capture_output=True,
            text=True
        )
        
        if result.stdout.strip():
            for line in result.stdout.strip().split('\\n'):
                if line.strip():
                    file_path = Path(line.strip())
                    try:
                        # Remove world-write permission
                        current_mode = file_path.stat().st_mode
                        new_mode = current_mode & ~0o002  # Remove world-write
                        file_path.chmod(new_mode)
                        print(f"  - Fixed permissions for {file_path}")
                    except Exception as e:
                        print(f"Error fixing permissions for {file_path}: {e}")
                        
    except Exception as e:
        print(f"Error in permission check: {e}")

def main():
    """Main remediation function"""
    print("Starting automated compliance remediation...")
    
    fix_security_headers()
    remove_hardcoded_secrets()
    fix_file_permissions()
    
    print("\\nCompliance remediation completed")
    print("Please review all changes and test thoroughly before deploying")

if __name__ == "__main__":
    main()
'''

def main():
    """Main entry point"""
    parser = argparse.ArgumentParser(description="Generate automated remediation scripts")
    parser.add_argument("--type", required=True, choices=["dependencies", "code", "container", "compliance"], help="Type of remediation to generate")
    parser.add_argument("--output", required=True, type=Path, help="Output script path")
    
    args = parser.parse_args()
    
    generator = RemediationGenerator()
    generator.generate_remediation(args.type, args.output)
    
    print(f"Generated remediation script: {args.output}")

if __name__ == "__main__":
    main()
