version: "3.9"

services:
  api:
    build: .
    container_name: ml-model-api
    ports:
      - "8000:8000"
    environment:
      - ENV=production
      - DEBUG=false
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: ml-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mlmodel
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: ml-cache
    ports:
      - "6379:6379"